when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.7-jdk17-alpine@sha256:fe23613b689558d07160bea892975429946f7ed61ba69f2a42888c7e54d582f5
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
